replicaCount: 1

image:
  repository: registry.bare.pandrosion.org/zerocarbon/team-a/projects/deploy/spark-connect-kubernetes #ghrc.io/aagumin/spark-connect-kubernetes
  tag: 3.5.4-java17-python #3.5.4 #1.0.0
  pullPolicy: Always
  imagePullSecrets: 
    - name: regcred #[]

nameOverride: ""
fullnameOverride: ""

spark:
  eventLog:
    enabled: true
    dir: ""

  celeborn:
    enabled: false
    masterEndpoints: ""

  dynamicAllocation:
    enabled: false

  awsEndpoint: ""

  driver:
    cores: 2
    memoryMiB: 2048
    memoryOverheadMiB: 384
    ephemeralLocalVolume: {}
    affinity: {}
    tolerations: []

  executor:
    cores: 1
    requestCoresMilliCPU: 2000
    memoryMiB: 2048
    memoryOverheadMiB: 384
    ephemeralLocalVolume: {}
    minExecutors: 1
    maxExecutors: 2
    affinity: {}
    tolerations: []
    labels: {}

  scratchDir: /tmp
  kubernetesEndpoint: "https://kubernetes.default.svc.cluster.local:443"
  packages: []
  sparkConfig:
    spark.hadoop.parquet.block.size: "33554432"
    spark.driver.maxResultSize: 4g

  catalog:
    enabled: false
    hiveMetastoreConfigMap: spark-connect-hive

serviceAccount:
  create: true
  annotations: {}
  name: "spark-connect"
  automountServiceAccountToken: true

service:
  create: true
  annotations: {}
  name: "spark-connect"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsUser: 185
  runAsGroup: 185

command: []
extraArgs: []
extraEnv: []

mtls:
  enabled: false
  prestartscript: ""
  poststopscript: ""

containerPorts:
  sparkUi: 4040
  sparkConnect: 15002
